services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USERNAME: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      TZ: 'GMT'
      PGTZ: 'GMT'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
      - ./config/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

volumes:
  db_data:
    driver: local
